### PR TITLE
feat: send nil as a parameter since this is not in request context

### PR DESCRIPTION
**Pull request by mrigesh**
This is to support compatibility with rk-entry PR  https://github.com/rookie-ninja/rk-entry/pull/72 , post successful merge of rk-entry, rk-boot needs to be updated with new version of rk-ektry

### CODE REVIEW

**Comment by mrigesh** [comment]
@dongxuny please review

**Review by dongxuny — APPROVED** [review]
LGTM

**Comment by dongxuny** [comment]
@mrigesh Please bump rk-entry version to v2.2.18 in go.mod file which contains your latest commits.

**Comment by mrigesh** [comment]
@dongxuny done.

**Comment by dongxuny** [comment]
I will upgrade rk-entry version in rk-xxx family either.

**Comment by mrigesh** [comment]
@dongxuny thank you. This bump should only affect rk-boot, since it's a breaking change. It should not have any effect on other modules. do let me know if anything has to be done on my side.

**Comment by dongxuny** [comment]
@mrigesh No problem, I checked other modules, it is good to bump rk-entry version in other module safely. If there is any error occurs while using rk-boot, please upgrade the rk-xxx version. I will finish upgrading rk-xxx module in an hour.

**Comment by mrigesh** [comment]
@dongxuny awesome. Sounds good.

**Pull request merged**
